image: jelaniwoods/appdev2022-base-rails:winter-test
tasks:
  - command: bundle install
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public
  - port: 9515
    onOpen: ignore

vscode:
  extensions:
    - vortizhe.simple-ruby-erb
    - mbessey.vscode-rufo
    - aliariff.vscode-erb-beautify

